import './sass/main.scss';
import './js/event-search';
import './js/select';
import './js/modalClose';
import './js/firstPageLoad.js';
import './js/pagination';
import './js/modal_our_team';
import './js/renderEventIntoModal.js';
import './js/morefromauthor.js';
import './js/notify_iziToast'
